name: .NET develop
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build_for_develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./FinTech-SQ011B-PaymentService/
      run: dotnet restore
    - name: Build
      working-directory: ./FinTech-SQ011B-PaymentService/
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./FinTech-SQ011B-PaymentService/
      run: dotnet test --no-build --verbosity normal
